### ISSUE TITLE
[Bug] Module not adding currency but everything else to loot pile

### ISSUE THREAD

**Issue by e11aprope11a** [etriebe/dnd-randomizer#102]
Foundry Build 315, dnd-randomizer 1.0.59, I'm also using Item Piles 2.9.1 and tidy 5e sheets 3.3.1
![photo_2024-04-20_22-13-45](https://github.com/etriebe/dnd-randomizer/assets/167649084/18604066-63b9-4783-84a4-18e69f96bda2)

**Comment by etriebe** [comment]
Fixed with latest release.

**Comment by e11aprope11a** [comment]
That was fast, thanks a lot!!
