### ISSUE TITLE
Encounters generation not working, compendiums indexing generate empty index files

### ISSUE THREAD

**Issue by StreamZero** [etriebe/dnd-randomizer#19]
- **ALL OTHER MODULES DISABLED?** true
- **Module:** dnd-randomizer 1.0.14
- **Foundry and System version**: Foundry 10.286, DnD5e 2.0.3
- **OS, Hosting, Browser (if applicable)**: Windows 11, Local, Chrome
- **Short Description of bug**: Compendiums indexing always generate empty index json files, generation of new encounters does not work regardless of indexing option in settings. 
- **Simple steps to reproduce the bug**: Install module, open module windows, open compendium filter, select any compendium with actors in it (eg. ***Monsters (SRD)***), index/force re-index, click on generate encounters.
- **Screenshots and/or console errors**: 

```
localmodule.js:275 ReferenceError: SFLOCALCONSTS is not defined
    at ActorUtils.getActorEnvironments (ActorUtils.js:99:39)
    at new NPCActor5e (NPCActor5e.js:15:39)
    at ActorUtils.getActorObject (ActorUtils.js:50:16)
    at SFLocalHelpers.populateMonstersFromCompendiums (localmodule.js:256:42)
    at async Promise.all (index 1)
    at async SFLocalHelpers.populateObjectsFromCompendiums (localmodule.js:63:9)
    at async HTMLButtonElement.<anonymous> (compendium.js:85:23)
populateMonstersFromCompendiums @ localmodule.js:275
await in populateMonstersFromCompendiums (async)
populateObjectsFromCompendiums @ localmodule.js:62
(anonymous) @ compendium.js:85
await in (anonymous) (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
```
localmodule.js:276 Actor id shhHtE7b92PefCWB, name Aboleth failed to get added.
populateMonstersFromCompendiums @ localmodule.js:276
await in populateMonstersFromCompendiums (async)
populateObjectsFromCompendiums @ localmodule.js:62
(anonymous) @ compendium.js:85
await in (anonymous) (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
(Repeated for every actor in the selected compendiums)

**PS**: (Experienced in version 1.0.13) Treasure hoards magic items are listed as "undefined" entries below encounter monsters, but when the selected encounter is spawned or generated as loot-only, the relative "loot actor" has all the correct defined magic item in it, clickable and draggable.

**PPS**: (Experienced in version 1.0.13) When selecting the **Random** encounter type option and generating encounters, the listed actors are clickable but no actor window pops up, while the correct actor window pops up if any other encounter type option is selected.

Let me know if I have to open other issue posts and thanks for your work, this module is quite useful!

**Comment by etriebe** [comment]
I believe this was resolved a month ago. Can you confirm? @StreamZero

**Comment by StreamZero** [comment]
Thanks, the main problem is solved, compendium indexing and encounters generation are both working.

These issues are still present in the current latest releases of Foundry (10.288) and this module (1.0.15):
> PS: (Experienced in version 1.0.13) Treasure hoards magic items are listed as "undefined" entries below encounter monsters, but when the selected encounter is spawned or generated as loot-only, the relative "loot actor" has all the correct defined magic item in it, clickable and draggable.

> PPS: (Experienced in version 1.0.13) When selecting the Random encounter type option and generating encounters, the listed actors are clickable but no actor window pops up, while the correct actor window pops up if any other encounter type option is selected.

**Comment by etriebe** [comment]
Fixed! Sorry for the delay! I now have the repository fully monitored. :)
