### ISSUE TITLE
Can not place monsters in scene with template

### ISSUE THREAD

**Issue by jxj5034** [etriebe/dnd-randomizer#21]
The encounter generator successfully creates a list of encounters. However, when clicking Spawn Encounter, and then placing a template, the tokens are not placed on the map and the console generates errors:

**ALL OTHER MODULES DISABLED?** True
**Module:** dnd-randomizer v1.0.15
**Conflicting Module (if applicable)**: None
**Foundry and System version**: Foundry Version 10 build 290.  + DnD5e Fifth Edition 2.0.3
**OS, Hosting, Browser (if applicable)**:
**Short Description of bug**: The encounter generator successfully creates a list of encounters. However, when clicking Spawn Encounter, and then placing a template, the tokens are not placed on the map and the console generates errors:
**Simple steps to reproduce the bug**:
1. Click "Generate Encounter" on the actor tab
2. Configure desired settings (changing the parameters of the generator does not change the result)
3. Click "Generate Encounters" in the Encounter Generator Window
4. Choose any encounter and click "Spawn Encounter" button
5. Template appears. Dropping template (left click) does not spawn tokens into scene
6. Actors are created in the Actor tab under the SF-Creatures folder.
**Screenshots and/or console errors**:

Please place a Circle Template to Spawn the Encounter
foundry.js:29773 Uncaught (in promise) Error: A valid wall restriction type is required for testCollision.
[Detected 1 package: dnd-randomizer]
    at Function.testCollision (foundry.js:29773)
    at WallsLayer.checkCollision (foundry.js:37420)
    at Function.randomInCircle (spawner.js:80)
    at Function.fromTemplate (spawner.js:16)
﻿
​

**Comment by jxj5034** [comment]
Additionally, when clicking "Generate Encounters", the console outputs additional errors related to the treasure hoard:





1617 monsters loaded from cache date 2022-11-29 14:32:34 
EncounterUtils5e.js:412 Unable to generate Treasure Horde for maximum CR 7 and d100 roll of 54. Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
getTreasureHordeForEncounter @ EncounterUtils5e.js:412
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:539
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:413 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getRandomItemFromRollTable (FoundryUtils.js:123)
    at Function.getMagicItemResult (EncounterUtils5e.js:469)
    at Function.getTreasureHordeForEncounter (EncounterUtils5e.js:408)
    at Function.getLootForEncounter (EncounterUtils5e.js:267)
    at Function.createEncounterDnd5e (EncounterUtils5e.js:168)
    at Function.createEncounters (localmodule.js:539)
    at HTMLButtonElement.<anonymous> (dialog.js:302)
getTreasureHordeForEncounter @ EncounterUtils5e.js:413
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:539
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:412 Unable to generate Treasure Horde for maximum CR 4 and d100 roll of 79. Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
getTreasureHordeForEncounter @ EncounterUtils5e.js:412
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:413 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getRandomItemFromRollTable (FoundryUtils.js:123)
    at Function.getMagicItemResult (EncounterUtils5e.js:469)
    at Function.getTreasureHordeForEncounter (EncounterUtils5e.js:408)
    at Function.getLootForEncounter (EncounterUtils5e.js:267)
    at Function.createEncounterDnd5e (EncounterUtils5e.js:168)
    at Function.createEncounters (localmodule.js:549)
    at HTMLButtonElement.<anonymous> (dialog.js:302)
getTreasureHordeForEncounter @ EncounterUtils5e.js:413
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:412 Unable to generate Treasure Horde for maximum CR 4 and d100 roll of 42. Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
getTreasureHordeForEncounter @ EncounterUtils5e.js:412
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:413 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getRandomItemFromRollTable (FoundryUtils.js:123)
    at Function.getMagicItemResult (EncounterUtils5e.js:469)
    at Function.getTreasureHordeForEncounter (EncounterUtils5e.js:408)
    at Function.getLootForEncounter (EncounterUtils5e.js:267)
    at Function.createEncounterDnd5e (EncounterUtils5e.js:168)
    at Function.createEncounters (localmodule.js:549)
    at HTMLButtonElement.<anonymous> (dialog.js:302)
getTreasureHordeForEncounter @ EncounterUtils5e.js:413
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:412 Unable to generate Treasure Horde for maximum CR 4 and d100 roll of 64. Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
getTreasureHordeForEncounter @ EncounterUtils5e.js:412
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:413 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getRandomItemFromRollTable (FoundryUtils.js:123)
    at Function.getMagicItemResult (EncounterUtils5e.js:469)
    at Function.getTreasureHordeForEncounter (EncounterUtils5e.js:408)
    at Function.getLootForEncounter (EncounterUtils5e.js:267)
    at Function.createEncounterDnd5e (EncounterUtils5e.js:168)
    at Function.createEncounters (localmodule.js:549)
    at HTMLButtonElement.<anonymous> (dialog.js:302)
getTreasureHordeForEncounter @ EncounterUtils5e.js:413
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:412 Unable to generate Treasure Horde for maximum CR 4 and d100 roll of 41. Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
getTreasureHordeForEncounter @ EncounterUtils5e.js:412
getLootForEncounter @ EncounterUtils5e.js:267
createEncounterDnd5e @ EncounterUtils5e.js:168
createEncounters @ localmodule.js:549
(anonymous) @ dialog.js:302
async function (async)
(anonymous) @ dialog.js:300
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
EncounterUtils5e.js:413 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getRandomItemFromRollTable (FoundryUtils.js:123)
    at Function.getMagicItemResult (EncounterUtils5e.js:469)
    at Function.getTreasureHordeForEncounter (EncounterUtils5e.js:408)
    at Function.getLootForEncounter (EncounterUtils5e.js:267)
    at Function.createEncounterDnd5e (EncounterUtils5e.js:168)
    at Function.createEncounters (localmodule.js:549)
    at HTMLButtonElement.<anonymous> (dialog.js:302)

**Comment by kuchrk24** [comment]
I am receiving the same error. I actually posted in therippers discord as I did not know this module transferred hands. The above user reported the issue over a month ago. Is this module no longer being developed?

**Comment by etriebe** [comment]
For some reason I wasn't getting notifications for this. Let me take a look now. Sorry about the delay!

**Comment by etriebe** [comment]
Fixed! Sorry for the delay! I now have the repository fully monitored. :)

**Comment by kuchrk24** [comment]
When is this fix going to be released?

**Comment by etriebe** [comment]
It should already be released. Are you not seeing it working after updating?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kuchrk24** [comment]
I regularly update my foundry modules and this one has yet to be updated. The latest release for this accourding to github is October 1st 2022.
![image](https://user-images.githubusercontent.com/74018852/213929706-a63207eb-bbdf-4c47-bfb8-d4e23bc0ed65.png)

**Comment by etriebe** [comment]
Ah shoot! Just generated a new release! Should be out in a few minutes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kuchrk24** [comment]
Got it. Thank you
