### ISSUE TITLE
Journal formatting missing when dnd-randomizer Module is enabled

### ISSUE THREAD

**Issue by germandrewboat** [etriebe/dnd-randomizer#22]
See issue described here and following 3 messages: 

https://discord.com/channels/170995199584108546/956307084931112960/1049215542101299230

![stoch](https://user-images.githubusercontent.com/90376395/205578434-b2769556-8e17-47ff-9e90-4bae2fa49cb3.png)

**Comment by germandrewboat** [comment]
![image](https://user-images.githubusercontent.com/90376395/205783916-8bf65eda-4f15-4234-9778-fb3168642323.png)

Screenshot of the messages I linked to if discord link isn't good enough.

**Comment by etriebe** [comment]
Weiiiird bug! Let me think about how this might be happening. My guess is CSS class names.

**Comment by etriebe** [comment]
Fixed! Sorry for the delay! I now have the repository fully monitored. :)
