### ISSUE TITLE
Can't place an encounter

### ISSUE THREAD

**Issue by Nuku** [etriebe/dnd-randomizer#28]
I generated a bunch of encounters. Should they have names or just numbers? Clicked one, dragged a circle.
![image](https://user-images.githubusercontent.com/886729/214691068-0927dea0-5395-4fc8-9250-c22f7e718348.png)
No monsters resulted.

**Comment by Nuku** [comment]
Clicking create loot creates a loot object with nothing in it. PF2e.

**Comment by etriebe** [comment]
Should have names and numbers. Would you he able to DM me details to login to your world if you don't mind? Check my github profile for contact info.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: David Silver ***@***.***>
Sent: Wednesday, January 25, 2023 1:08:29 PM
To: etriebe/dnd-randomizer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [etriebe/dnd-randomizer] Can't place an encounter (Issue #28)


I generated a bunch of encounters. Should they have names or just numbers? Clicked one, dragged a circle.
[image]<https://user-images.githubusercontent.com/886729/214691068-0927dea0-5395-4fc8-9250-c22f7e718348.png>
No monsters resulted.

**Comment by Nuku** [comment]
Email fired!

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/214698837-284281ea-754a-448d-82f1-aa05bdc68f33.png)
