### ISSUE TITLE
The reindex button does not function

### ISSUE THREAD

**Issue by matthewswar** [etriebe/dnd-randomizer#3]
Clicking the button results in an error in the console with the following message

> A subclass of the FormApplication must implement the _updateObject method.

This seems to be caused by the removal of the listener on the button in [this diff](https://github.com/etriebe/dnd-randomizer/commit/df9a4e5c97594195390e7af3d43c284f544852bd#diff-25cddecb5ab342c63af6a95c9a58510c10316867bb7c2d645e974766ab91eabdL68). It looks like it may have mistakenly been added to the environment chooser, or the reindex button itself hasn't been moved to that dialog yet.

**Comment by etriebe** [comment]
Just saw this. Checking.

**Comment by etriebe** [comment]
Fixed with commit 990e40c9b94646876b42135323168ce0250892b6.

**Comment by etriebe** [comment]
Fixed in this release.

https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.4
