### ISSUE TITLE
Slow Generation

### ISSUE THREAD

**Issue by Nuku** [etriebe/dnd-randomizer#35]
PF2, when clicking to generate encounters, it takes quite a bit of time, like 10sh minutes. Any way to speed this up? Love the module, just to be clear. Super fantastic, but if we could fix that...

**Comment by etriebe** [comment]
I did notice this too when I added loot generation... Let me see if there is a way to improve this.

**Comment by etriebe** [comment]
Just put in the above release. Should be nearly instant now.
