### ISSUE TITLE
[PF2E] Downloaded 1.0.22 not sure its working 

### ISSUE THREAD

**Issue by BasiliskOnline** [etriebe/dnd-randomizer#37]
Edit: nevermind, i refreshed my server and now im seeing stuff, so its possible that it just needed a ton of time to index my compendiums? which was not indicated in the information here on github or by any sort of pop up. Checking it now.

And now it works.

**Comment by etriebe** [comment]
Can you press F12 and screenshot or paste the error you see.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: BasiliskOnline ***@***.***>
Sent: Tuesday, February 28, 2023 12:09:21 PM
To: etriebe/dnd-randomizer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [etriebe/dnd-randomizer] [PF2E] Downloaded 1.0.22 not sure its working (Issue #37)


Hey, so I saw this mod posted in the PF2E Foundry discord and it looked cool, so i downloaded it. But I cant seem to get it to work?

I ran generation after setting up a prompt but i cancelled it after 5 minutes (timed). Is it supposed to take longer than that? Or is there something extra I have to do to give it access to the PF2E compendiums it doesnt normally?

**Comment by BasiliskOnline** [comment]
So I see a few thing in F12 (I reloaded my server so all my cached compendiums are gone, but i think it IS working on getting them indexed or whatever its just taking a while which is fine just nice to have a warning somewhere about that xD 

but I do see some stuff
![image](https://user-images.githubusercontent.com/27906526/221972191-922846fa-50cf-4719-b1dc-f0dd67113c44.png)
and a lot of these:
![image](https://user-images.githubusercontent.com/27906526/221972341-d5c79501-e11d-4abe-b6b1-bf5d04b6ee65.png)

Again, it DOES seem to be working, and once the compendiums are all indexed it is also pretty quick, just getting everything loaded in so it can work seems tricky. last time it just started working did a flurry of "downloading assets" and then worked fine.

(while it was working it worked very nicely tho, just trying to figure out how this works xD)

**Comment by etriebe** [comment]
Ah yeah, indexing can take a while. I can try and put a warning and maybe progress notifications.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BasiliskOnline** [comment]
sorry to reopen had a few questions about that because im trying it on a fresh server right now. 
(progress and warning would be great tho! so we know its doign something)
I started up a fresh game to make sure it wasnt a mod conflict... im now 8 minutes in to load up and its still not indexed, this entire thing would be fine if it didnt seem to be EVERY time you booted up your server?

(when i logged out and logged back in on my old server everything was no longer indexed? is there a way to keep previous indexation? is it supposed to?)

**Comment by etriebe** [comment]
You shouldn't be seeing super long wait times on each load unless it isn't saving the cache for some reason. Can you possibly email me login details to your world (email in my profile).

**Comment by etriebe** [comment]
Should be fixed now. Please let me know if it isn't! @BasiliskOnline
