### ISSUE TITLE
Only Showing Blank Encounters

### ISSUE THREAD

**Issue by magniventris** [etriebe/dnd-randomizer#4]
Hi there! I'm having a bit of trouble with the 'Stochastic, Fantastic!' module. Whenever I try to load an encounter using a custom compendium, it only returns blank encounters. I figured it might be because the compendium I was using was pretty small and not complete, so I went ahead and imported the names and CRs of everything I would be using and remade the compendium, but that still didn't help. I then made a new compendium of a bunch of random monsters, and I'm still having the same issue. I've tried disabling all other modules, uninstalling and reinstalling, and checked the console, but I've never found anything obviously wrong. Thank you in advance!

**Comment by etriebe** [comment]
If there are no obvious errors, it'd be best to share with me access to your world as an admin and I can dig in. If it is a small compendium, my guess is that is the cause but I can confirm.

**Comment by etriebe** [comment]
https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.5
