### ISSUE TITLE
Different totals of monsters

### ISSUE THREAD

**Issue by Nuku** [etriebe/dnd-randomizer#41]
![image](https://user-images.githubusercontent.com/886729/228638529-2b1cc5f7-5b85-495d-b69c-011399b71826.png)
Under creature type
![image](https://user-images.githubusercontent.com/886729/228638773-abb3b578-dda3-4824-870f-d9c833581365.png)
Under environment
So which is true? Shouldn't 'any' for both be the same?

**Comment by etriebe** [comment]
Hm... I'll try and take a look. I think the dynamic creature type should
have fixed this but perhaps there are still some bugs here. Can you confirm
what version you were using?

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/229234753-eddc7fd6-8532-41a9-8123-3de0cdaf1e79.png)

**Comment by etriebe** [comment]
@Nuku Let me know if this isn't fixed for you!

**Comment by Nuku** [comment]
Nope, still very different numbers.
![image](https://github.com/etriebe/dnd-randomizer/assets/886729/27b2c842-8c44-4a1f-bca6-7e7e87de61c8)

![image](https://github.com/etriebe/dnd-randomizer/assets/886729/9b0c0194-8485-4a00-bd44-8dd0a3782162)
