### ISSUE TITLE
The Forge-specific considerations and possible improvements

### ISSUE THREAD

**Issue by rikmarais** [etriebe/dnd-randomizer#43]
The Forge uses distributed storage, meaning that any call to browse() introduces some latency.

The `ensureFolder` and `fileExists` methods in `localmodule` could possibly be improved in two ways:

- The searched folder and file name paths could be cached, so that the same run won't make a browse call to the same target multiple times.

- The source can be configured. For example, instead of calling against `"data"`, you can call directly against `"forgevtt"` if you are running on The Forge. This means that there does not need to be a redirect and The Forge can look the folder up in its Assets Library directly.
```js
      let source = (typeof ForgeVTT != "undefined" && ForgeVTT.usingTheForge) ? "forgevtt" : "data";
```

There is one more thing: in `fileExists`, there is a check for the file existing by comparing the full file path to the response returned from the browse. This will not work on The Forge, since a relative path is searched for but a full URL to the Assets Library is returned.
If the `source` is `"forgevtt"`, it could help to use `f.endsWith(fullFilePath);` instead of `if (cacheDir.files.filter(f => f === fullFilePath).length > 0)` to check for the file existing.

Thanks for reading this issue, I understand that it may not be a high priority but these improvements would greatly increase performance for users on The Forge using this great module. Currently, they're not able to benefit from the caching features and have to reconstruct the index from compendiums every time, which can take a while with network calls.

**Comment by etriebe** [comment]
I've always knows about this but haven't had a forge instance to be able to investigate. This is a fantastic bug report so I'll take a look at what I can do!

**Comment by etriebe** [comment]
@rikmarais let me know if this update fixed things for you! Great suggestions and made my work a lot easier. 🙏
