### ISSUE TITLE
Look into search box not working

### ISSUE THREAD

**Issue by etriebe** [etriebe/dnd-randomizer#52]

**Comment by etriebe** [comment]
@Dragonubis do you have version information for foundry, d&d5e/pf2e (whichever you're using)? And console logs?

**Comment by Dragonubis** [comment]
here are the versions, were can i get the console logs?

![image](https://github.com/etriebe/dnd-randomizer/assets/151975738/49d12252-91af-4eb7-b248-36edc4d1201a)

![image](https://github.com/etriebe/dnd-randomizer/assets/151975738/99e6d99d-836a-4c4d-b0bc-a9b44413a2de)

**Comment by Dragonubis** [comment]
![image](https://github.com/etriebe/dnd-randomizer/assets/151975738/5d6eab66-017c-4866-b8d6-db6a757ba556)

**Comment by Dragonubis** [comment]
[Encounter Generator Error 12.8.2023.txt](https://github.com/etriebe/dnd-randomizer/files/13621697/Encounter.Generator.Error.12.8.2023.txt)

**Comment by Dragonubis** [comment]
Hope the information helps!

**Comment by etriebe** [comment]
Fixed your issue in this release. @Dragonubis 

https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.49

I believe you had a creature with an undefined creature type, somehow. Given no one has reported this before, I think this is specific to you, but should add some resiliency no matter what.

**Comment by Dragonubis** [comment]
thanks, I will test and let you know soon!

**Comment by lebonslkb** [comment]
I had the same problem and it wasn't solve by the new release. Foundry v11.315, DnD5e v2.4.1 and the last version 1.0.49 of the module.

**Comment by etriebe** [comment]
@lebonslkb @Dragonubis could one of you DM me on discord? I might need access to your world to dig into why this is happening.

**Comment by etriebe** [comment]
@lebonslkb can you check now? I just updated and I think this should fix it again. There was pf2e specific code being used for dnd5e, breaking everything for dnd.

**Comment by lebonslkb** [comment]
No, I'm sending you an invite the world on your gmail.

**Comment by etriebe** [comment]
Can you attach/screenshot your console logs for the error?

**Comment by etriebe** [comment]
Can you screenshot/attach the console logs? @lebonslkb

**Comment by etriebe** [comment]
@Dragonubis is this fixed for you yet?

**Comment by lebonslkb** [comment]
vTools failed to load source map: Could not load content for http://localhost:30000/modules/dnd-randomizer/scripts/lib/gridjs.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Dragonubis** [comment]
> @lebonslkb @Dragonubis could one of you DM me on discord? I might need access to your world to dig into why this is happening.

I don't have your discord but you can add me. Should be the same username: Dragonubis

**Comment by lebonslkb** [comment]
I'm on Discord: user lebonslkb

**Comment by etriebe** [comment]
@lebonslkb the source map issue is just a warning. That can be ignored. 

The issue should be fixed now in this release. 

https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.51
