### ISSUE TITLE
Not selecting creatures with PF2e

### ISSUE THREAD

**Issue by Telain** [etriebe/dnd-randomizer#53]
Foundry 10.291
PF2e 4.12.9
module 1.0.32
I have confirmed that there are actors available.

Generating with treasure but no enemies. All entries show "Needs -15 XP adjustment"

Sometimes generation instead hangs with the below error immediately showing up in the Console:
dialog.js:239 

Uncaught (in promise) TypeError: undefined. npcActorObject.analyzeActor is not a function
[Detected 1 package: dnd-randomizer]
    at SFDialog.populateEncounters (dialog.js:239:26)
    at async HTMLButtonElement.<anonymous> (dialog.js:331:4)
populateEncounters @ dialog.js:239
await in populateEncounters (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by etriebe** [comment]
Taking a look!

**Comment by Telain** [comment]
Awesome! Thanks for the quick fix. Updated and properly populating encounters now.
