### ISSUE TITLE
Missing icons on generated loot (v11)

### ISSUE THREAD

**Issue by zdaar** [etriebe/dnd-randomizer#58]
![image](https://github.com/etriebe/dnd-randomizer/assets/4218386/d9e32178-6ecf-4ba5-9563-21ac8a7d24a8)

Icons were moved to core (note sure when, I just recently updated to v11 from v9) and the paths have changed for those

https://github.com/etriebe/dnd-randomizer/blob/8c6be46537b095b6dc0d0f8a852d93d1bfbf87b0/scripts/main.js#L33

they are now in

icons/containers/bags

**Comment by etriebe** [comment]
Should be resolved now, I believe. Let me know if you see issues.
