### ISSUE TITLE
Generation Not Working

### ISSUE THREAD

**Issue by kirerellim** [etriebe/dnd-randomizer#78]
![received_286903117677663](https://github.com/etriebe/dnd-randomizer/assets/39993026/bee40f7f-f27a-4c81-a9d0-3bc0c20b060f)
Running a fresh world with just this module activated but can't generate encounters. Everything is based settings, I get this error.

Does the module have requirements I need that I missed?

**Comment by etriebe** [comment]
Hm... Let me check.
