### ISSUE TITLE
"null" name error

### ISSUE THREAD

**Issue by ctbritt** [etriebe/dnd-randomizer#82]
I keep getting this error when using my ddb imported compendium: 
![CleanShot 2023-12-14 at 12 33 14@2x](https://github.com/etriebe/dnd-randomizer/assets/4516034/d869deb4-a850-42b8-87cd-c55176aaf2b5)

There's something wrong with one of the monsters, but I can't. tell which one. Any advice on finding that, or adding a check that will skip monsters with a null value for name?

**Comment by etriebe** [comment]
Can you paste that without your URL in the way (also to prevent your URL from somehow being grabbed from some on-looker)? Text copy is fine too.

I can add a check that would skip that but I could probably just as easily tell you which monster is messed up. :)

**Comment by ctbritt** [comment]
thanks!

**Comment by etriebe** [comment]
Can you ping me on discord? I might need access to your world. I have what *should* be a check to handle this but it isn't working (clearly). I can add some defense in depth with that but would need to debug locally.
