### ISSUE TITLE
Can't Generate BBEG + Anything

### ISSUE THREAD

**Issue by e0m00p2** [etriebe/dnd-randomizer#84]
I can't seem to generate any bbeg + combo. It can't find anything that fits it seems. Is this just that the srd doesn't have enough options?

I have disabled all other modules: True
Module(s) Stochastic, Fantastic! 1.0.53
Conflicting Module(s) 
Foundry and System version Fvtt V11 build 315
OS, Hosting, Browser (if applicable) Windows 11 hosting 

![image](https://github.com/etriebe/dnd-randomizer/assets/124808698/de60ba5a-112a-4813-bcc3-1dfd95dca4db)

**Comment by Nuku** [comment]
Same problem: 
![image](https://github.com/etriebe/dnd-randomizer/assets/886729/66cf01e0-fbee-4200-a905-e90b29b3c1e8)
PF2 over here.

**Comment by etriebe** [comment]
Is this still broken? Sorry about the delay! I can't tell if this was after the release I made or before.

**Comment by etriebe** [comment]
For @e0m00p2 i think the issue was your filters were too extreme and there were no creatures near that XP level with those filters. So having more creatures will help with that OR having less extreme filters.

**Comment by Nuku** [comment]
![image](https://github.com/etriebe/dnd-randomizer/assets/886729/fec86bee-855c-4c0e-94c8-a192ea3a22b1)

**Comment by etriebe** [comment]
@Nuku can you attach console logs? I wanna see if there are failures.

**Comment by Nuku** [comment]
![image](https://github.com/etriebe/dnd-randomizer/assets/886729/2e5dc725-770a-4de9-8367-27d655b6efeb)
Skipping creature Kappa, id QrD96KPUHGjjkLbL b/c not same creature type plant as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Toy Swarm, id pmxHr6pbQMLY3Ltq b/c not same creature type humanoid as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Soulbound Doll (Chaotic Evil), id 7EpLGBoddL8Vzlha b/c not same creature type construct as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Dovan from Nisroch, id eVHkWtrdGJMVMob7 b/c not same creature type humanoid as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Icicle Snake, id veyyE0brfjIoQK1q b/c not same creature type animal,humanoid as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Tengu Sneak, id 70JDH25JLTC4t5Ko b/c not same creature type ethereal,spirit as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Giant Porcupine, id IijUBFE1vhvgowhD b/c not same creature type dragon as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Warg, id Sft7n3LMmnTxhhYn b/c not same creature type aberration as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Terror Bird, id rnxg09tUCFPGW8IS b/c not same creature type dragon as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Domovoi, id NhHGDx6ChbrhAmbO b/c not same creature type humanoid as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Spark Bat, id jpjhbGvaduK4iqwq b/c not same creature type aberration as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Rat Snake Swarm, id 60bknqrpHs2lL4pt b/c not same creature type animal as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Ice Zuggle, id ChLImKXE82rV2foE b/c not same creature type construct as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Duergar Taskmaster, id dEecX0AEfl32KUVN b/c not same creature type fiend,giant,humanoid as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Black Kobold Dragon Mage, id R9eoGwQ2tudxUKxS b/c not same creature type construct as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Draugr, id 48agy7vl9fQW1LLA b/c not same creature type animal as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Fungus Leshy, id oiXbo1VSfDrHpIQm b/c not same creature type beast as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Lustspawn, id x8ZWNcFOfpJYjXOw b/c not same creature type aberration as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Lizardfolk Stargazer, id yzyaD2yGDrxmYh7P b/c not same creature type beast as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Tengu Sneak, id 70JDH25JLTC4t5Ko b/c not same creature type aberration as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Soulbound Doll (Lawful Good), id RAjbVzWcfrPBbgkK b/c not same creature type beast as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Animated Armor, id cZDiyluplFqRxmGy b/c not same creature type elemental as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Flaming Skull, id FvywQFbFzwLV8mvW b/c not same creature type dragon,elemental as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Crystalline Owl, id mlnha6g2gxH9hxL8 b/c not same creature type aberration as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Azarketi Explorer, id RTTs4lvkcPz8u6IY b/c not same creature type dragon as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Animated Armor, id cZDiyluplFqRxmGy b/c not same creature type dragon as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Black Bear, id xxP5FJotshmUQNtY b/c not same creature type beast as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Paintbrush Fox, id JIxEb7vP55yGgGWH b/c not same creature type fey as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Tengu Sneak, id 70JDH25JLTC4t5Ko b/c not same creature type fungus as previous monster.
EncounterUtilsPf2e.js:60 Skipping creature Faerie Dragon, id atrhmCtNKx1MR06I b/c not same creature type aberration,dream as previous monster.

**Comment by Nuku** [comment]
![image](https://github.com/etriebe/dnd-randomizer/assets/886729/f94229b5-dbb4-4605-950e-ef3c1b8337d1)

**Comment by etriebe** [comment]
OK, that's helpful! I think it is accidentally using same type instead of variety. Looking!

**Comment by etriebe** [comment]
Fixed with most recent release!

**Comment by etriebe** [comment]
Heads up I'm having trouble releasing right now. Stay tuned.

**Comment by e0m00p2** [comment]
I did happen to find a work around just today, amusingly. As you said, its accidently using the same type instead of variety. It says variety as default. But, if you change the same type, run it, then change to variety, it works lol

**Comment by etriebe** [comment]
Yep. The bug was that the default *said* it was variety but it was actually defaulted to single. So if you switch it fixed it but if you don’t touch anything it’s broken.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by etriebe** [comment]
Released! Let me know if this works for you all!

**Comment by e0m00p2** [comment]
works perfect, you're awesome!
