### ISSUE TITLE
Generation not working correctly. dnd 5e

### ISSUE THREAD

**Issue by kridak-krushbones** [etriebe/dnd-randomizer#89]
When i generate an encounter i only see the first monster...other monsters it says "missing xp target"

Hoping this image shows up.

I assume i am doing something wrong.

![image](https://github.com/etriebe/dnd-randomizer/assets/157236000/c7fac976-d0a9-4ab4-bbd2-9a3903b0fb07)

**Comment by etriebe** [comment]
My best guess is you don't have creatures that can fulfill the requirement for a lower level based on those filters. Are you filtering but environment or creature type?

If you press F12 it'll say more in console logs. If you save those off it'll be more helpful.

**Comment by kridak-krushbones** [comment]
Weird it fixed itself when i hit the variety button and changed it to single then back to variety...very weird.

Thanks for this it awesome for wandering monster for overland travel.

**Comment by etriebe** [comment]
Yep, the bug was in the default values being switched to single but the UI showing "Variety of".
