### ISSUE TITLE
Cache Location

### ISSUE THREAD

**Issue by Shuggaloaf** [etriebe/dnd-randomizer#9]
I know this is a minor thing, but would it be possible to move the cache folder and files to within the module folder itself, rather than the root data folder? I'm not sure if there's a technical reason for it's location, but it would just be cleaner and more inline with most mods if you could. Again, I know it's a small thing but if possible, when you have time, it would be appreciated.

**Comment by etriebe** [comment]
I removed the cache! It is no longer necessary. 😄
