### ISSUE TITLE
[Bug] PF2e unable to index compendiums, resulting in no actors being used in generation.

### ISSUE THREAD

**Issue by Derinzed** [etriebe/dnd-randomizer#91]
Foundry version: 10
Foundry Build: 303

PF2e System version: 4.12.9

Description:
As stated in the title, if you open the creature codex with a fresh install (not disabling or altering filters) you will receive no actors in the list.  If you open the inspection menu, you will notice multiple errors stating that the compendiums could not be indexed.  This results in the generator being unable to create encounters with valid actors and the codex being left empty.  This was reproducible in a fresh world without any other modules. Images below showing the errors:

![image](https://github.com/etriebe/dnd-randomizer/assets/45581121/96278c11-43e1-4e4f-8d23-ff615daa3a36)

**Comment by etriebe** [comment]
Ah, creature codex shouldn't work for pf2e since they already have the creature browser, I think, as part of built in PF2E.

**Comment by etriebe** [comment]
But I will fix it to not let the button appear for PF2E.

**Comment by Derinzed** [comment]
Awesome i appreciate it.  As a followup question...is it expected that when you generate encounters, all encounters display "missing level x"  and do not spawn creatures?

**Comment by etriebe** [comment]
Do you have a screenshot and a copy of console logs I can look at,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Derinzed** [comment]
Sure. Here's a screen of the generator:

![image](https://github.com/etriebe/dnd-randomizer/assets/45581121/0762d268-c163-4ecf-83a2-169cbbf439a1)

Same thing will happen across any selection.

**Comment by etriebe** [comment]
OK, so what creatures do you have selected and what filter settings?

**Comment by Derinzed** [comment]
Also, if it's helpful information. I'm using all compendiums, and have a filter with 3 level 3 players.

**Comment by Derinzed** [comment]
For kicks and giggles, I updated to foundry V.11.  It appears to be working as intended now.  I'm guessing this is only an issue in V10, but I'm going to downgrade and see.

**Comment by etriebe** [comment]
Let me try and figure out what fix broke this for V10 and add a v10 vs v11 pivot.

**Comment by Derinzed** [comment]
Sounds good.  I did get it to work previously.  Under Scripts/Utils/ActorUtils.js I changed line 25:

![image](https://github.com/etriebe/dnd-randomizer/assets/45581121/2a58e140-815f-48be-94c0-1937b4fccb49)

To be honest I'm not sure if everything works 100% as expected as I hadn't tested much before hand, but this does appear to resolve the issue on a surface level.

**Comment by etriebe** [comment]
Fixed with latest release.
